import TopLoaderProvider from "@/components/provider/top-loader-provider";
import Footer from "@/components/shared/footer/footer";
import SiteNavbar from "@/components/shared/navbar/navbar";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <TopLoaderProvider />
                <SiteNavbar />
                {/* paddint top 60px because SiteNavbar is fixed position */}
                <main className="pt-[60px] section ">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
